"""add_chunk_and_embedding_tables

Revision ID: 869d6099bb33
Revises: 20baecb4d9ef
Create Date: 2026-06-04 15:01:24.962055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '869d6099bb33'
down_revision: Union[str, None] = '20baecb4d9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension — must run before any table with a vector column is created.
    # Without this, PostgreSQL does not recognize the 'vector' type.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunking_strategy', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('layout_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['document_extraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunk_chunking_strategy'), 'document_chunk', ['chunking_strategy'], unique=False)
    op.create_index(op.f('ix_document_chunk_extraction_id'), 'document_chunk', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_uuid'), 'document_chunk', ['uuid'], unique=True)
    op.create_table('chunk_embedding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_embedding_chunk_id'), 'chunk_embedding', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_embedding_uuid'), 'chunk_embedding', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_embedding_uuid'), table_name='chunk_embedding')
    op.drop_index(op.f('ix_chunk_embedding_chunk_id'), table_name='chunk_embedding')
    op.drop_table('chunk_embedding')
    op.drop_index(op.f('ix_document_chunk_uuid'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_extraction_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_chunking_strategy'), table_name='document_chunk')
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
